### ISSUE TITLE
Error in ini parser

### ISSUE THREAD

**Issue by bostjan** [a2o/snoopy#44]
Originally reported by @ajzach in issue #39:
```
__GI_abort () at abort.c:125
        act = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {18446744073709551615 <repeats 16 times>}}, 
          sa_flags = 0, sa_restorer = 0x0}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2104 0x00007f7b9bdc3925 in os::abort(bool) () from /usr/lib/jvm/java-7-oracle/jre/lib/amd64/server/libjvm.so
No symbol table info available.
#2105 0x00007f7b9bf42827 in VMError::report_and_die() () from /usr/lib/jvm/java-7-oracle/jre/lib/amd64/server/libjvm.so
No symbol table info available.
#2106 0x00007f7b9bdc82af in JVM_handle_linux_signal () from /usr/lib/jvm/java-7-oracle/jre/lib/amd64/server/libjvm.so
No symbol table info available.
#2107 <signal handler called>
No locals.
#2108 iniparser_getboolean (d=d@entry=0x7f7b189690d0, key=key@entry=0x7f7b9ce274d8 "snoopy:error_logging", notfound=notfound@entry=-1)
    at iniparser/src/iniparser.c:478
        c = 0x0
#2109 0x00007f7b9ce2435d in snoopy_configuration_load_file (iniFilePath=iniFilePath@entry=0x7f7b9ce27550 "/etc/snoopy.ini") at configuration.c:194
        ini = 0x7f7b189690d0
        confValString = <optimized out>
        confValInt = <optimized out>
#2110 0x00007f7b9ce2444c in snoopy_configuration_ctor () at configuration.c:107
No locals.
#2111 0x00007f7b9ce24b57 in snoopy_init () at misc.c:56
No locals.
#2112 0x00007f7b9ce24a5d in snoopy_log_syscall (syscallName=syscallName@entry=0x7f7b9ce27426 "execve") at log.c:378
        logMessage = 0x0
#2113 0x00007f7b9ce24b43 in snoopy_log_syscall_execve (filename=filename@entry=0x7f7b1173c8a0 "/usr/local/bin/git", argv=argv@entry=0x7f7b187e88b0, 
    envp=envp@entry=0x7f7b18aa3fc0) at log.c:348
No locals.
#2114 0x00007f7b9ce23d25 in execve (filename=0x7f7b1173c8a0 "/usr/local/bin/git", argv=0x7f7b187e88b0, envp=0x7f7b18aa3fc0) at libsnoopy.c:76
        func = 0x7f7b9c4d9330 <__execve>
#2115 0x00007f7b9ac7824a in execve_with_shell_fallback () from /usr/lib/jvm/java-7-oracle/jre/lib/amd64/libjava.so
No symbol table info available.
#2116 0x00007f7b9ac7849f in JDK_execvpe () from /usr/lib/jvm/java-7-oracle/jre/lib/amd64/libjava.so
No symbol table info available.
#2117 0x00007f7b9ac78c9d in startChild () from /usr/lib/jvm/java-7-oracle/jre/lib/amd64/libjava.so
No symbol table info available.
#2118 0x00007f7b9ac7906b in Java_java_lang_UNIXProcess_forkAndExec () from /usr/lib/jvm/java-7-oracle/jre/lib/amd64/libjava.so
No symbol table info available.
---Type <return> to continue, or q <return> to quit---
```

@ajzach comment (copied from #39):
No, all problems occur in the forkAndExec of Java, it can be that there is a problem of concurrency?

**Comment by bostjan** [comment]
@ajzach: could you please test this with master 5c3578a0?

For Snoopy 2.3.0 release iniparser component has been upgraded to latest git version (3.1 which is used in snoopy 2.2.x is from year 2012).

Tnx,
b.

**Comment by bostjan** [comment]
I think this one should be fixed now. Iniparser has been upgraded to 4.0, and optional threading support has been added in 2.4.0.

Closing for now.
