### ISSUE TITLE
Double free or corruption

### ISSUE THREAD

**Issue by ajzach** [a2o/snoopy#47]
Bug in master:

```
#2106 __GI_abort () at abort.c:125
        act = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {18446744073709551615 <repeats 16 times>}}, 
          sa_flags = 0, sa_restorer = 0x0}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2107 0x00007fd8fa1f3394 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7fd8fa301b28 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/posix/libc_fatal.c:175
        ap = {{gp_offset = 40, fp_offset = 32728, overflow_arg_area = 0x7fd85c275470, reg_save_area = 0x7fd85c275400}}
        fd = 2
        on_2 = <optimized out>
        list = <optimized out>
        nlist = <optimized out>
        cp = <optimized out>
        written = <optimized out>
---Type <return> to continue, or q <return> to quit---
#2108 0x00007fd8fa1ff66e in malloc_printerr (ptr=<optimized out>, str=0x7fd8fa301c58 "double free or corruption (out)", action=1) at malloc.c:4996
        buf = "00007fd8b84d1b50"
        cp = <optimized out>
#2109 _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3840
        size = <optimized out>
        fb = <optimized out>
        nextchunk = <optimized out>
        nextsize = <optimized out>
        nextinuse = <optimized out>
        prevsize = <optimized out>
        bck = <optimized out>
        fwd = <optimized out>
        errstr = <optimized out>
        locked = <optimized out>
#2110 0x00007fd8fab8bd89 in snoopy_configuration_dtor () at configuration.c:128
No locals.
#2111 0x00007fd8fab8cb57 in snoopy_cleanup () at misc.c:75
No locals.
#2112 0x00007fd8fab8ca98 in snoopy_log_syscall (syscallName=syscallName@entry=0x7fd8fab8f396 "execve") at log.c:398
        logMessage = <optimized out>
#2113 0x00007fd8fab8cb33 in snoopy_log_syscall_execve (filename=filename@entry=0x7fd85c2755a0 "/usr/bin/git", argv=argv@entry=0x7fd8dc0247b0, 
    envp=envp@entry=0x7fd8dc044f60) at log.c:348
No locals.
#2114 0x00007fd8fab8bd35 in execve (filename=0x7fd85c2755a0 "/usr/bin/git", argv=0x7fd8dc0247b0, envp=0x7fd8dc044f60) at libsnoopy.c:76
        func = 0x7fd8fa241330 <__execve>
#2115 0x00007fd8f891ee8e in execve_with_shell_fallback () from /usr/lib/jvm/java-8-oracle/jre/lib/amd64/libjava.so
No symbol table info available.
#2116 0x00007fd8f891f0e1 in JDK_execvpe () from /usr/lib/jvm/java-8-oracle/jre/lib/amd64/libjava.so
No symbol table info available.
#2117 0x00007fd8f891f4fb in childProcess () from /usr/lib/jvm/java-8-oracle/jre/lib/amd64/libjava.so
No symbol table info available.
#2118 0x00007fd8f891c474 in vforkChild () from /usr/lib/jvm/java-8-oracle/jre/lib/amd64/libjava.so
No symbol table info available.
#2119 0x00007fd8f891cdc0 in Java_java_lang_UNIXProcess_forkAndExec () from /usr/lib/jvm/java-8-oracle/jre/lib/amd64/libjava.so

```

**Comment by bostjan** [comment]
Did you configure filter chain in snoopy.ini when you got this error?

b.

**Comment by bostjan** [comment]
@ajzach Ariel: what tool do you use to get these backtraces you usually provide? It seems quite handy (verbosity-wise).

Tnx if you can share that,
b.

**Comment by ajzach** [comment]
I use gdb.

**Comment by bostjan** [comment]
Tnx.

b.
